# Generated by Django 5.1.3 on 2024-11-11 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblUsuario',
            fields=[
                ('usu_codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('usu_nome', models.CharField(max_length=255)),
                ('usu_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TblTarefas',
            fields=[
                ('tar_codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('tar_descricao', models.CharField(max_length=255)),
                ('tar_setor', models.CharField(max_length=255)),
                ('tar_prioridade', models.CharField(max_length=255)),
                ('tar_data', models.DateField()),
                ('usu_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tblusuario')),
            ],
        ),
    ]
