# Generated by Django 5.1.3 on 2024-11-15 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usu_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('usu_nome', models.CharField(max_length=255)),
                ('usu_email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('tar_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('tar_descricao', models.CharField(max_length=255)),
                ('tar_setor', models.CharField(max_length=255)),
                ('tar_prioridade', models.CharField(max_length=20)),
                ('tar_status', models.CharField(max_length=20)),
                ('tar_data', models.DateField()),
                ('usu_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.usuario')),
            ],
        ),
    ]
