# Generated by Django 5.1.3 on 2024-11-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='tar_prioridade',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Média', 'Média'), ('Baixa', 'Baixa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='tar_status',
            field=models.CharField(choices=[('Completa', 'Completa'), ('Pendente', 'Pendente')], max_length=20),
        ),
    ]
