# Generated by Django 5.1.3 on 2024-11-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_tarefa_tar_prioridade_alter_tarefa_tar_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='tar_prioridade',
            field=models.CharField(max_length=20),
        ),
    ]
